# Generated by Django 4.1.9 on 2023-05-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_birth',
            new_name='date_of_birth',
        ),
    ]
